export type PlatformRoute = {
  path: string;
  screen: string;
  area: "platform" | "tenant-admin" | "patient" | "public";
  shell?: string;
};

export const platformRoutes: PlatformRoute[] = [
  { path: "/", screen: "Navigate to /login", area: "platform" },
  { path: "/login", screen: "PlatformLogin", area: "platform" },
  { path: "/register", screen: "TenantOnboarding", area: "platform" },
  { path: "/platform-dashboard", screen: "PlatformDashboard", area: "platform" },
  { path: "/tenants/:id", screen: "TenantDetails", area: "platform" },
  { path: "/tenants/:id/settings", screen: "TenantSettings", area: "platform" },
  { path: "/dashboard", screen: "Dashboard", area: "tenant-admin" },
  { path: "/super-admin", screen: "SuperAdminDashboard", area: "tenant-admin" },
  { path: "/appointments", screen: "AppointmentsPage", area: "tenant-admin" },
  { path: "/calendar", screen: "Calendar", area: "tenant-admin" },
  { path: "/patients", screen: "PatientsPage", area: "tenant-admin" },
  { path: "/patients/:id", screen: "PatientsPage", area: "tenant-admin" },
  { path: "/medicines", screen: "MedicinesManagement", area: "tenant-admin" },
  { path: "/lab-tests", screen: "LabTests", area: "tenant-admin" },
  { path: "/procedures", screen: "Procedures", area: "tenant-admin" },
  { path: "/consultation", screen: "Consultation", area: "tenant-admin" },
  { path: "/completed-appointments", screen: "CompletedAppointments", area: "tenant-admin" },
  { path: "/settings", screen: "Settings", area: "tenant-admin" },
  { path: "/new-appointment", screen: "NewAppointment", area: "tenant-admin" },
  { path: "/admin/ambulances", screen: "AmbulancesPage", area: "tenant-admin" },
  { path: "/admin/staffs/calls", screen: "StaffCallList", area: "tenant-admin" },
  { path: "/admin/staffs/list", screen: "StaffFleetList", area: "tenant-admin" },
  { path: "/admin/staffs/details/:id", screen: "StaffDetails", area: "tenant-admin" },
  { path: "/admin/ambulances/calls", screen: "AmbulanceCallList", area: "tenant-admin" },
  { path: "/admin/ambulances/list", screen: "AmbulanceFleetList", area: "tenant-admin" },
  { path: "/admin/ambulances/details/:id", screen: "AmbulanceDetails", area: "tenant-admin" },
  { path: "/admin/ambulances/dispatch", screen: "AmbulanceDispatch", area: "tenant-admin" },
  { path: "/admin/pharmacy/medicines", screen: "PharmacyMedicines", area: "tenant-admin" },
  { path: "/admin/pharmacy/inventory", screen: "PharmacyInventory", area: "tenant-admin" },
  { path: "/admin/blood-bank/stock", screen: "BloodStock", area: "tenant-admin" },
  { path: "/admin/blood-bank/donors", screen: "BloodDonors", area: "tenant-admin" },
  { path: "/admin/blood-bank/issued", screen: "BloodIssued", area: "tenant-admin" },
  { path: "/admin/blood-bank/add-unit", screen: "AddBloodUnit", area: "tenant-admin" },
  { path: "/admin/blood-bank/issue", screen: "IssueBlood", area: "tenant-admin" },
  { path: "/admin/feedback", screen: "Feedback", area: "tenant-admin" },
  { path: "/admin/rooms/alloted", screen: "RoomsAlloted", area: "tenant-admin" },
  { path: "/admin/rooms/new", screen: "NewAllotment", area: "tenant-admin" },
  { path: "/admin/rooms", screen: "Rooms", area: "tenant-admin" },
  { path: "/admin/reviews", screen: "Reviews", area: "tenant-admin" },
  { path: "/admin/pending-tasks", screen: "PendingTasks", area: "tenant-admin" },
  { path: "/admin/billing", screen: "InvoicesList", area: "tenant-admin" },
  { path: "/admin/billing/new", screen: "CreateInvoice", area: "tenant-admin" },
  { path: "/admin/billing/invoices/:id", screen: "InvoiceDetail", area: "tenant-admin" },
  { path: "/admin/billing/payments", screen: "PaymentsHistory", area: "tenant-admin" },
  { path: "/admin/hospital/profile", screen: "HospitalProfile", area: "tenant-admin" },
  { path: "/admin/hospital/departments", screen: "Departments", area: "tenant-admin" },
  { path: "/admin/hospital/infrastructure", screen: "Infrastructure", area: "tenant-admin" },
  { path: "/admin/finance/revenue", screen: "FinanceRevenue", area: "tenant-admin" },
  { path: "/admin/finance/insurance", screen: "InsuranceClaims", area: "tenant-admin" },
  { path: "/admin/lab/pending", screen: "LabPendingTests", area: "tenant-admin" },
  { path: "/admin/lab/revenue", screen: "LabRevenue", area: "tenant-admin" },
  { path: "/admin/compliance/audit-logs", screen: "AuditLogs", area: "tenant-admin" },
  { path: "/admin/compliance/access-control", screen: "AccessControl", area: "tenant-admin" },
  { path: "/admin/compliance/data-access", screen: "DataAccessLogs", area: "tenant-admin" },
  { path: "/admin/notifications/system", screen: "SystemAlerts", area: "tenant-admin" },
  { path: "/admin/notifications/settings", screen: "NotificationSettings", area: "tenant-admin" },
  { path: "/admin/reports/daily", screen: "DailyReports", area: "tenant-admin" },
  { path: "/admin/reports/monthly", screen: "MonthlyReports", area: "tenant-admin" },
  { path: "/admin/reports/doctor-revenue", screen: "DoctorRevenueReport", area: "tenant-admin" },
  { path: "/admin/reports/department-revenue", screen: "DepartmentRevenueReport", area: "tenant-admin" },
  { path: "/admin/feedback/patient", screen: "PatientFeedback", area: "tenant-admin" },
  { path: "/admin/feedback/doctor-ratings", screen: "DoctorRatings", area: "tenant-admin" },
  { path: "/admin/feedback/complaints", screen: "ComplaintsManagement", area: "tenant-admin" },
  { path: "/admin/feedback/quality-score", screen: "ServiceQualityScore", area: "tenant-admin" },
  { path: "/admin/config/appointment-rules", screen: "AppointmentRules", area: "tenant-admin" },
  { path: "/admin/config/pricing-rules", screen: "PricingRules", area: "tenant-admin" },
  { path: "/admin/config/tax-settings", screen: "TaxSettings", area: "tenant-admin" },
  { path: "/admin/config/payment-gateways", screen: "PaymentGateways", area: "tenant-admin" },
  { path: "/admin/config/messaging", screen: "MessagingIntegrations", area: "tenant-admin" },
  { path: "/admin/config/website", screen: "WebsiteSettings", area: "tenant-admin" },
  { path: "/admin/config/theme-templates", screen: "ThemeTemplates", area: "tenant-admin" },
  { path: "/admin/emr/diagnosis", screen: "EMRDiagnosisNotes", area: "tenant-admin" },
  { path: "/admin/emr/treatment-plans", screen: "EMRTreatmentPlans", area: "tenant-admin" },
  { path: "/admin/emr/progress-notes", screen: "EMRProgressNotes", area: "tenant-admin" },
  { path: "/admin/emr/documents", screen: "EMRDocuments", area: "tenant-admin" },
  { path: "/admin/follow-ups", screen: "FollowUps", area: "tenant-admin" },
  { path: "/admin/care-plans", screen: "CarePlans", area: "tenant-admin" },
  { path: "/admin/telemedicine", screen: "Telemedicine", area: "tenant-admin" },
  { path: "/admin/schedule", screen: "DoctorSchedule", area: "tenant-admin" },
  { path: "/admin/tasks", screen: "TasksNotifications", area: "tenant-admin" },
  { path: "/admin/analytics", screen: "DoctorAnalytics", area: "tenant-admin" },
  { path: "/admin/communication", screen: "Communication", area: "tenant-admin" },
  { path: "/admin/emergency", screen: "EmergencyAlerts", area: "tenant-admin" },
  { path: "/admin/profile", screen: "DoctorProfileSettings", area: "tenant-admin" },
  { path: "/patient/dashboard", screen: "PatientHome", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/appointments", screen: "PatientAppointments", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/appointments/book", screen: "PatientBookAppointment", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/appointments/history", screen: "PatientAppointmentHistory", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/records", screen: "PatientMedicalRecords", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/records/visits", screen: "PatientMedicalRecords", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/records/diagnoses", screen: "PatientMedicalRecords", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/records/doctor-notes", screen: "PatientMedicalRecords", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/records/discharge", screen: "PatientMedicalRecords", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/records/documents", screen: "PatientMedicalRecords", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/prescriptions", screen: "PatientPrescriptions", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/prescriptions/current", screen: "PatientPrescriptions", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/prescriptions/history", screen: "PatientPrescriptions", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/prescriptions/refill", screen: "PatientPrescriptions", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/lab-reports", screen: "PatientLabReports", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/lab-reports/pending", screen: "PatientLabReports", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/lab-reports/completed", screen: "PatientLabReports", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/lab-reports/radiology", screen: "PatientLabReports", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/billing", screen: "PatientBilling", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/billing/invoices", screen: "PatientBilling", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/billing/payments", screen: "PatientBilling", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/billing/insurance", screen: "PatientBilling", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/timeline", screen: "PatientHealthTimeline", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/messages", screen: "PatientMessages", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/upload-reports", screen: "PatientUploadReports", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/support", screen: "PatientSupport", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/notifications", screen: "PatientNotifications", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/profile", screen: "PatientProfile", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/family", screen: "PatientProfile", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/telemedicine", screen: "PatientTelemedicine", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/feedback", screen: "PatientFeedbackPage", area: "patient", shell: "PatientConsoleShell" },
  { path: "/patient/settings", screen: "PatientSettings", area: "patient", shell: "PatientConsoleShell" }
];

export const componentCoverage = {
  contexts: ["AuthProvider", "CustomAuthProvider", "AppointmentProvider", "TabAccessProvider"],
  layouts: ["ConsoleShell", "PatientConsoleShell"],
  dashboardTabs: ["DashboardTabs", "DashboardKPICards", "SuperAdminGraphs", "SuperAdminKPICards", "PatientsTab", "PrescriptionsTab", "ScheduleTab", "StatsTab", "TasksTab"],
  ui: [
    "accordion",
    "alert",
    "alert-dialog",
    "aspect-ratio",
    "avatar",
    "badge",
    "breadcrumb",
    "button",
    "calendar",
    "card",
    "carousel",
    "chart",
    "checkbox",
    "collapsible",
    "command",
    "context-menu",
    "dialog",
    "drawer",
    "dropdown-menu",
    "form",
    "hover-card",
    "input",
    "input-otp",
    "label",
    "menubar",
    "navigation-menu",
    "pagination",
    "popover",
    "progress",
    "radio-group",
    "resizable",
    "scroll-area",
    "select",
    "separator",
    "sheet",
    "sidebar",
    "skeleton",
    "slider",
    "sonner",
    "switch",
    "table",
    "tabs",
    "textarea",
    "toast",
    "toaster",
    "toggle",
    "toggle-group",
    "tooltip"
  ]
};
